### ISSUE TITLE
Determine sequence and workflow for change request #1

### ISSUE THREAD

**Issue by XUMINSHENG** [XUMINSHENG/VMCS#1]
Bug found on R1.0.8 with priority level-urgent

**Comment by achyut92** [comment]
![defect](https://cloud.githubusercontent.com/assets/11267409/9875462/cb706bbc-5be0-11e5-9c40-b91fce6a60aa.png)
Hi Jiabo,
  Please make the required changes in order to fix the bug. Check the CR for reference.

**Comment by xiejiabao** [comment]
Fix the bug of data reset and unit text for it

**Comment by xiejiabao** [comment]
@sutejakanuri Please review and test.

**Comment by sutejakanuri** [comment]
The defect has been fixed. The document has been reviewed and the changes have been made.
This code is ready for UAT.

**Comment by tanujkhator** [comment]
Changes have been implemented as per request ...Approved for release

**Comment by XUMINSHENG** [comment]
Change request #1 has been implemented and released in R1.0.9.
Issue closed.
