### ISSUE TITLE
Determine sequence and workflow for change request #2

### ISSUE THREAD

**Issue by XUMINSHENG** [XUMINSHENG/VMCS#2]
enhancement approved As the impact analysis suggests  less than 30 days of work

**Comment by achyut92** [comment]
Hi Avishek,
   Please check the updated CR and make the analysis for the new requirement requested by the User.

**Comment by AvishekDB** [comment]
Created Branch ChangeRequest-2
CR-2: Update design and Generate DesignModelReport
-Added Sequence diagrams for Update Coin Display, CoinLabelItem, CoinLabelItemDisplay
-Added "GetTotalCoin" operation for Store Controller class
-Remove association of CoinDisplay to ButtonItemDisplay
-Add association of CoinDisplay to CoinLabelItemDisplay
- Added "DisplayTotalCoin", "SetActiveTotalCoin" operations for Maintenance Panel class

**Comment by proliuxz** [comment]
According to the update design and Generate Design Model Report.
2 class(CoinLabelItem and CoinLabelItemDisplay) have been created to make the display clearly.
The other classes have been modified to fit the new display item.
Please check it.
Here is the Hyperlink: https://github.com/XUMINSHENG/VMCS/commit/14508d7ce1ae102296ad7a4773e33ecaa277332d
Thanks.

**Comment by sutejakanuri** [comment]
The code has been updated according to the enhancement requirement.
The document has been updated to reflect the new enhancement.
This code is ready for UAT.

**Comment by tanujkhator** [comment]
Changes have been implemented as per the request ....Approved for release

**Comment by XUMINSHENG** [comment]
Change request #2 has been implemented and released in R1.0.9.
Issue closed.
